pharmacie_api:
    resource: "@PharmacieApiBundle/Resources/config/routing.yml"
    prefix:   /

pharmacie_core:
    resource: "@PharmacieCoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
